/* EXERCÍCIO DE FIXAÇÃO - REQUISITOS

SR. JOSÉ QUER MODERNIZAR A SUA OFICINA, E POR ENQUANTO, CADASTRAR OS CARROS QUE ENTRAM PARA RELIZAR SERVIÇOS E OS SEUS RESPECTIVOS DONOS. SR. JOSÉ MENCIONOU QUE CADA CLIENTE POSSUI APENAS UM CARRO. UM CARRO POSSUI UMA MARCA. SR. JOSÉ TAMBÉM QUER SABER AS CORES DOS CARROS PARA TER IDEIA DE QUAL TINTA COMPRAR, E INFORMA QUE UM CARRO PODE TER MAIS DE UMA COR. SR. JOSÉ NECESSITA ARMAZENAR OS TELEFONES DOS CLIENTES MAS NÃO QUER QUE ELES SEJAM OBRIGATÓRIOS */



CREATE DATABASE OFICINA;
USE OFICINA;

/*--------------------
---------------------
CRIAÇÃO DAS TABELAS
---------------------
---------------------*/

CREATE TABLE CLIENTES (
    ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    PRIMEIRONOME VARCHAR (15) NOT NULL,
    ULTIMONOME VARCHAR (15) NOT NULL,
    SEXO ENUM ('M', 'F') NOT NULL,
    ID_VEICULO INT UNIQUE
);

CREATE TABLE VEICULOS (
    ID_VEICULO INT PRIMARY KEY AUTO_INCREMENT,
    MODELO VARCHAR (20) NOT NULL,
    ANO INT,
    ID_MARCA INT
);

CREATE TABLE MARCA (
    ID_MARCA INT PRIMARY KEY AUTO_INCREMENT,
    MARCA VARCHAR(30) UNIQUE

);

CREATE TABLE COR (
    ID_COR INT PRIMARY KEY AUTO_INCREMENT,
    COR VARCHAR (15) NOT NULL UNIQUE
    
);

CREATE TABLE TELEFONE (
    ID_TELEFONE INT PRIMARY KEY AUTO_INCREMENT,
    TIPO ENUM ('COM', 'RES', 'CEL') NOT NULL,
    NUMERO INT NOT NULL,
    ID_CLIENTE INT
);

CREATE TABLE VEICULO_COR(
    ID_COR INT,
    ID_VEICULO INT,
    PRIMARY KEY (ID_VEICULO, ID_COR)
);


/*------------
CONSTRAINTS
-------------*/

ALTER TABLE TELEFONE
ADD CONSTRAINT FK_TELEFONE_CLIENTE
FOREIGN KEY (ID_CLIENTE)
REFERENCES CLIENTES (ID_CLIENTE);

ALTER TABLE CLIENTES
ADD CONSTRAINT FK_CLIENTE_VEICULO
FOREIGN KEY (ID_VEICULO)
REFERENCES VEICULOS (ID_VEICULO);

ALTER TABLE VEICULOS
ADD CONSTRAINT FK_VEICULO_MARCA
FOREIGN KEY (ID_MARCA)
REFERENCES MARCA (ID_MARCA);

ALTER TABLE VEICULO_COR
ADD CONSTRAINT FK_VEICULO
FOREIGN KEY (ID_VEICULO)
REFERENCES VEICULOS (ID_VEICULO);

ALTER TABLE VEICULO_COR
ADD CONSTRAINT FK_COR
FOREIGN KEY (ID_COR)
REFERENCES COR (ID_COR);



/*-------------------
---------------------
INSERÇÃO DE VALORES 
---------------------
---------------------*/

INSERT INTO MARCA VALUES (NULL, 'HONDA');
INSERT INTO MARCA VALUES (NULL, 'FIAT');
INSERT INTO MARCA VALUES (NULL, 'CALOI');

INSERT INTO VEICULOS VALUES (NULL, 'CALOI 10', 2018, 3);
INSERT INTO VEICULOS VALUES (NULL, 'UNO', 2003, 2);
INSERT INTO VEICULOS VALUES (NULL, 'BIZ', 2015, 1);
INSERT INTO VEICULOS VALUES (NULL, 'MOBI', 2019, 2);

INSERT INTO CLIENTES VALUES (NULL, 'RAFAEL', 'NUNES', 'M', 3);
INSERT INTO CLIENTES VALUES (NULL, 'HENRIQUE', 'SILVEIRA', 'M', 4);
INSERT INTO CLIENTES VALUES (NULL, 'MARCELA', 'MIRANDA', 'F', 1);
INSERT INTO CLIENTES VALUES (NULL, 'AUGUSTA', 'DOS REIS', 'F', 2);


INSERT INTO COR VALUES (NULL, 'AZUL');
INSERT INTO COR VALUES (NULL, 'PRETO');
INSERT INTO COR VALUES (NULL, 'DOURADO');
INSERT INTO COR VALUES (NULL, 'VERMELHO');
INSERT INTO COR VALUES (NULL, 'PRATEADO');

INSERT INTO TELEFONE VALUES (NULL, 'RES', 951951951, 4);
INSERT INTO TELEFONE VALUES (NULL, 'CEL', 789789789, 4);
INSERT INTO TELEFONE VALUES (NULL, 'COM', 854854854, 4);
INSERT INTO TELEFONE VALUES (NULL, 'CEL', 213213213, 1);
INSERT INTO TELEFONE VALUES (NULL, 'CEL', 963963963, 3);
INSERT INTO TELEFONE VALUES (NULL, 'COM', 258258258, 2);
INSERT INTO TELEFONE VALUES (NULL, 'CEL', 745745745, 2);

INSERT INTO VEICULO_COR VALUES (3, 1);
INSERT INTO VEICULO_COR VALUES (2, 1);
INSERT INTO VEICULO_COR VALUES (1, 2);
INSERT INTO VEICULO_COR VALUES (5, 3);
INSERT INTO VEICULO_COR VALUES (4, 4);
INSERT INTO VEICULO_COR VALUES (2, 4);



SELECT C.PRIMEIRONOME, C.ULTIMONOME, C.SEXO, T.NUMERO, T.TIPO, M.MARCA, V.MODELO, V.ANO, CR.COR 
FROM VEICULOS V
INNER JOIN CLIENTES C
ON V.ID_VEICULO = C.ID_VEICULO
INNER JOIN TELEFONE T
ON T.ID_CLIENTE = C.ID_CLIENTE
INNER JOIN MARCA M
ON M.ID_MARCA = V.ID_MARCA
INNER JOIN VEICULO_COR VC
ON VC.ID_VEICULO = V.ID_VEICULO
INNER JOIN COR CR
ON VC.ID_COR = CR.ID_COR;



+--------------+------------+------+-----------+------+-------+----------+------+----------+
| PRIMEIRONOME | ULTIMONOME | SEXO | NUMERO    | TIPO | MARCA | MODELO   | ANO  | COR      |
+--------------+------------+------+-----------+------+-------+----------+------+----------+
| RAFAEL       | NUNES      | M    | 213213213 | CEL  | HONDA | BIZ      | 2015 | PRATEADO |
| HENRIQUE     | SILVEIRA   | M    | 258258258 | COM  | FIAT  | MOBI     | 2019 | PRETO    |
| HENRIQUE     | SILVEIRA   | M    | 745745745 | CEL  | FIAT  | MOBI     | 2019 | PRETO    |
| HENRIQUE     | SILVEIRA   | M    | 258258258 | COM  | FIAT  | MOBI     | 2019 | VERMELHO |
| HENRIQUE     | SILVEIRA   | M    | 745745745 | CEL  | FIAT  | MOBI     | 2019 | VERMELHO |
| MARCELA      | MIRANDA    | F    | 963963963 | CEL  | CALOI | CALOI 10 | 2018 | PRETO    |
| MARCELA      | MIRANDA    | F    | 963963963 | CEL  | CALOI | CALOI 10 | 2018 | DOURADO  |
| AUGUSTA      | DOS REIS   | F    | 951951951 | RES  | FIAT  | UNO      | 2003 | AZUL     |
| AUGUSTA      | DOS REIS   | F    | 789789789 | CEL  | FIAT  | UNO      | 2003 | AZUL     |
| AUGUSTA      | DOS REIS   | F    | 854854854 | COM  | FIAT  | UNO      | 2003 | AZUL     |
+--------------+------------+------+-----------+------+-------+----------+------+----------+


